version: '3'
services:
  backend: 
    image: kenmoses/devops-backend:1.0.0
      
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    environment:
      PORT: 5000
      MONGODB_URI: 'mongodb://Ken:Kasee@172.20.0.2:27017'
  client:
    image: kenmoses/devops-client:1.0.0
    tty: true 
    ports:
      - 3000:3003
    volumes:
      - ./client:/app
    depends_on:
      - backend
    environment:
      PORT: 3000
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: Ken
      MONGO_INITDB_ROOT_PASSWORD: Kasee
    volumes:
      - test-vol:/data/db
volumes:
  test-vol: